//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RentCarModel", "MarcaCarro", "Marca", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentCarDynamicEnt.Model.Marca), "Carro", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentCarDynamicEnt.Model.Carro), true)]

#endregion

namespace RentCarDynamicEnt.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RentCarEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RentCarEntities object using the connection string found in the 'RentCarEntities' section of the application configuration file.
        /// </summary>
        public RentCarEntities() : base("name=RentCarEntities", "RentCarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RentCarEntities object.
        /// </summary>
        public RentCarEntities(string connectionString) : base(connectionString, "RentCarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RentCarEntities object.
        /// </summary>
        public RentCarEntities(EntityConnection connection) : base(connection, "RentCarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marca> Marcas
        {
            get
            {
                if ((_Marcas == null))
                {
                    _Marcas = base.CreateObjectSet<Marca>("Marcas");
                }
                return _Marcas;
            }
        }
        private ObjectSet<Marca> _Marcas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Carro> Carros
        {
            get
            {
                if ((_Carros == null))
                {
                    _Carros = base.CreateObjectSet<Carro>("Carros");
                }
                return _Carros;
            }
        }
        private ObjectSet<Carro> _Carros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marcas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarcas(Marca marca)
        {
            base.AddObject("Marcas", marca);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Carros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarros(Carro carro)
        {
            base.AddObject("Carros", carro);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentCarModel", Name="Carro")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carro : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Carro object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="modelo">Initial value of the Modelo property.</param>
        /// <param name="marcaId">Initial value of the MarcaId property.</param>
        public static Carro CreateCarro(global::System.Int64 id, global::System.String modelo, global::System.Int64 marcaId)
        {
            Carro carro = new Carro();
            carro.Id = id;
            carro.Modelo = modelo;
            carro.MarcaId = marcaId;
            return carro;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MarcaId
        {
            get
            {
                return _MarcaId;
            }
            set
            {
                OnMarcaIdChanging(value);
                ReportPropertyChanging("MarcaId");
                _MarcaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarcaId");
                OnMarcaIdChanged();
            }
        }
        private global::System.Int64 _MarcaId;
        partial void OnMarcaIdChanging(global::System.Int64 value);
        partial void OnMarcaIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentCarModel", "MarcaCarro", "Marca")]
        public Marca Marca
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("RentCarModel.MarcaCarro", "Marca").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("RentCarModel.MarcaCarro", "Marca").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marca> MarcaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("RentCarModel.MarcaCarro", "Marca");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marca>("RentCarModel.MarcaCarro", "Marca", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentCarModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        public static Cliente CreateCliente(global::System.Int64 id, global::System.String nome, global::System.String endereco)
        {
            Cliente cliente = new Cliente();
            cliente.Id = id;
            cliente.Nome = nome;
            cliente.Endereco = endereco;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentCarModel", Name="Marca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marca : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marca object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Marca CreateMarca(global::System.Int64 id, global::System.String nome)
        {
            Marca marca = new Marca();
            marca.Id = id;
            marca.Nome = nome;
            return marca;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentCarModel", "MarcaCarro", "Carro")]
        public EntityCollection<Carro> Carros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Carro>("RentCarModel.MarcaCarro", "Carro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Carro>("RentCarModel.MarcaCarro", "Carro", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
